---
triple:          'arm64-apple-darwin'
binary-path:     .1982A
relocations:
  - { offsetInCU: 0xD7, offset: 0xD7, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C40, symSize: 0x10 }
  - { offsetInCU: 0x4425, offset: 0x4425, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x3C628, symBinAddr: 0x10000C058, symSize: 0x0 }
  - { offsetInCU: 0xEA74, offset: 0xEA74, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1982A.cpp, symObjAddr: 0x1B4, symBinAddr: 0x100007DD4, symSize: 0x3C }
  - { offsetInCU: 0xEC75, offset: 0xEC75, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x130, symBinAddr: 0x100007D50, symSize: 0x84 }
  - { offsetInCU: 0xEC7D, offset: 0xEC7D, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1982A.cpp, symObjAddr: 0x1B4, symBinAddr: 0x100007DD4, symSize: 0x3C }
  - { offsetInCU: 0xECFC, offset: 0xECFC, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007C50, symSize: 0xF4 }
  - { offsetInCU: 0xEF22, offset: 0xEF22, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C40, symSize: 0x10 }
...
