---
triple:          'arm64-apple-darwin'
binary-path:     .main
relocations:
  - { offsetInCU: 0xDD, offset: 0xDD, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x0, symBinAddr: 0x100007C30, symSize: 0xF4 }
  - { offsetInCU: 0x435B, offset: 0x435B, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x417B0, symBinAddr: 0x10000C068, symSize: 0x0 }
  - { offsetInCU: 0x1028A, offset: 0x1028A, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_main.cpp, symObjAddr: 0x1A0, symBinAddr: 0x100007D90, symSize: 0x3C }
  - { offsetInCU: 0x10906, offset: 0x10906, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x140, symBinAddr: 0x100007D30, symSize: 0x60 }
  - { offsetInCU: 0x1098D, offset: 0x1098D, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x0, symBinAddr: 0x100007C30, symSize: 0xF4 }
...
