---
triple:          'arm64-apple-darwin'
binary-path:     .584C
relocations:
  - { offsetInCU: 0xD7, offset: 0xD7, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007B10, symSize: 0x10 }
  - { offsetInCU: 0xDF, offset: 0xDF, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x1F4, symBinAddr: 0x10000C070, symSize: 0x0 }
  - { offsetInCU: 0x7781, offset: 0x7781, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x447A8, symBinAddr: 0x10000C090, symSize: 0x0 }
  - { offsetInCU: 0x11CC6, offset: 0x11CC6, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_584C.cpp, symObjAddr: 0x270, symBinAddr: 0x100007D60, symSize: 0x3C }
  - { offsetInCU: 0x12106, offset: 0x12106, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x220, symBinAddr: 0x100007D10, symSize: 0x50 }
  - { offsetInCU: 0x1218A, offset: 0x1218A, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007B20, symSize: 0x1E4 }
  - { offsetInCU: 0x12192, offset: 0x12192, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x1F4, symBinAddr: 0x10000C070, symSize: 0x0 }
  - { offsetInCU: 0x1295A, offset: 0x1295A, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x1F4, symBinAddr: 0x10000C070, symSize: 0x0 }
  - { offsetInCU: 0x12A17, offset: 0x12A17, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007B10, symSize: 0x10 }
...
