---
triple:          'arm64-apple-darwin'
binary-path:     .1979B
relocations:
  - { offsetInCU: 0xD7, offset: 0xD7, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C50, symSize: 0x10 }
  - { offsetInCU: 0x4400, offset: 0x4400, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x3C138, symBinAddr: 0x10000C058, symSize: 0x0 }
  - { offsetInCU: 0xE946, offset: 0xE946, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1979B.cpp, symObjAddr: 0x184, symBinAddr: 0x100007DC4, symSize: 0x3C }
  - { offsetInCU: 0xEBA4, offset: 0xEBA4, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x100, symBinAddr: 0x100007D40, symSize: 0x84 }
  - { offsetInCU: 0xEBAC, offset: 0xEBAC, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1979B.cpp, symObjAddr: 0x184, symBinAddr: 0x100007DC4, symSize: 0x3C }
  - { offsetInCU: 0xEC2B, offset: 0xEC2B, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007C60, symSize: 0xD8 }
  - { offsetInCU: 0xEE2D, offset: 0xEE2D, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C50, symSize: 0x10 }
...
