---
triple:          'arm64-apple-darwin'
binary-path:     .999A
relocations:
  - { offsetInCU: 0xD6, offset: 0xD6, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007CF0, symSize: 0x10 }
  - { offsetInCU: 0x4426, offset: 0x4426, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x3C4D0, symBinAddr: 0x10000C050, symSize: 0x0 }
  - { offsetInCU: 0xEA73, offset: 0xEA73, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_999A.cpp, symObjAddr: 0x120, symBinAddr: 0x100007DF0, symSize: 0x3C }
  - { offsetInCU: 0xEC75, offset: 0xEC75, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0xD0, symBinAddr: 0x100007DA0, symSize: 0x50 }
  - { offsetInCU: 0xECF9, offset: 0xECF9, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007D00, symSize: 0x98 }
  - { offsetInCU: 0xEED3, offset: 0xEED3, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007CF0, symSize: 0x10 }
...
