---
triple:          'arm64-apple-darwin'
binary-path:     .1986A
relocations:
  - { offsetInCU: 0xD7, offset: 0xD7, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C40, symSize: 0x10 }
  - { offsetInCU: 0x440A, offset: 0x440A, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x3C220, symBinAddr: 0x10000C058, symSize: 0x0 }
  - { offsetInCU: 0xE950, offset: 0xE950, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1986A.cpp, symObjAddr: 0x1B4, symBinAddr: 0x100007DE4, symSize: 0x3C }
  - { offsetInCU: 0xEBAE, offset: 0xEBAE, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x130, symBinAddr: 0x100007D60, symSize: 0x84 }
  - { offsetInCU: 0xEBB6, offset: 0xEBB6, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1986A.cpp, symObjAddr: 0x1B4, symBinAddr: 0x100007DE4, symSize: 0x3C }
  - { offsetInCU: 0xEC35, offset: 0xEC35, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007C50, symSize: 0x104 }
  - { offsetInCU: 0xEEEC, offset: 0xEEEC, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C40, symSize: 0x10 }
...
