---
triple:          'arm64-apple-darwin'
binary-path:     .945A
relocations:
  - { offsetInCU: 0xD6, offset: 0xD6, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C50, symSize: 0x10 }
  - { offsetInCU: 0x440A, offset: 0x440A, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x3C2D8, symBinAddr: 0x10000C058, symSize: 0x0 }
  - { offsetInCU: 0xE94F, offset: 0xE94F, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_945A.cpp, symObjAddr: 0x1B4, symBinAddr: 0x100007DE4, symSize: 0x3C }
  - { offsetInCU: 0xEC39, offset: 0xEC39, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x130, symBinAddr: 0x100007D60, symSize: 0x84 }
  - { offsetInCU: 0xEC41, offset: 0xEC41, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_945A.cpp, symObjAddr: 0x1B4, symBinAddr: 0x100007DE4, symSize: 0x3C }
  - { offsetInCU: 0xECC0, offset: 0xECC0, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007C60, symSize: 0x100 }
  - { offsetInCU: 0xEFA2, offset: 0xEFA2, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C50, symSize: 0x10 }
...
