---
triple:          'arm64-apple-darwin'
binary-path:     .1974A
relocations:
  - { offsetInCU: 0xD7, offset: 0xD7, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C60, symSize: 0x10 }
  - { offsetInCU: 0x440A, offset: 0x440A, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x3C1D0, symBinAddr: 0x10000C058, symSize: 0x0 }
  - { offsetInCU: 0xE950, offset: 0xE950, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1974A.cpp, symObjAddr: 0x194, symBinAddr: 0x100007DE4, symSize: 0x3C }
  - { offsetInCU: 0xEBF5, offset: 0xEBF5, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x110, symBinAddr: 0x100007D60, symSize: 0x84 }
  - { offsetInCU: 0xEBFD, offset: 0xEBFD, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1974A.cpp, symObjAddr: 0x194, symBinAddr: 0x100007DE4, symSize: 0x3C }
  - { offsetInCU: 0xEC7C, offset: 0xEC7C, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007C70, symSize: 0xE4 }
  - { offsetInCU: 0xEE98, offset: 0xEE98, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007C60, symSize: 0x10 }
...
