---
triple:          'arm64-apple-darwin'
binary-path:     .1979C
relocations:
  - { offsetInCU: 0xD8, offset: 0xD8, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007920, symSize: 0x10 }
  - { offsetInCU: 0x4528, offset: 0x4528, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x430D8, symBinAddr: 0x10000C0B0, symSize: 0x0 }
  - { offsetInCU: 0x10588, offset: 0x10588, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1979C.cpp, symObjAddr: 0x404, symBinAddr: 0x100007CA4, symSize: 0x3C }
  - { offsetInCU: 0x10D3B, offset: 0x10D3B, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x380, symBinAddr: 0x100007C20, symSize: 0x84 }
  - { offsetInCU: 0x10D43, offset: 0x10D43, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1979C.cpp, symObjAddr: 0x404, symBinAddr: 0x100007CA4, symSize: 0x3C }
  - { offsetInCU: 0x10DC2, offset: 0x10DC2, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x10, symBinAddr: 0x100007930, symSize: 0x2E8 }
  - { offsetInCU: 0x1191A, offset: 0x1191A, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007920, symSize: 0x10 }
...
