---
triple:          'arm64-apple-darwin'
binary-path:     .1986B
relocations:
  - { offsetInCU: 0xD8, offset: 0xD8, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007520, symSize: 0x10 }
  - { offsetInCU: 0xE0, offset: 0xE0, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x5B0, symBinAddr: 0x10000C0C0, symSize: 0x0 }
  - { offsetInCU: 0x4624, offset: 0x4624, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x4B830, symBinAddr: 0x10000C140, symSize: 0x0 }
  - { offsetInCU: 0x12406, offset: 0x12406, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1986B.cpp, symObjAddr: 0x704, symBinAddr: 0x100007B54, symSize: 0x3C }
  - { offsetInCU: 0x12980, offset: 0x12980, size: 0x8, addend: 0x0, symName: __ZSt18__do_uninit_fill_nIPSt6vectorIiSaIiEEmS2_ET_S4_T0_RKT1_, symObjAddr: 0x30, symBinAddr: 0x100007550, symSize: 0x154 }
  - { offsetInCU: 0x12988, offset: 0x12988, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x184, symBinAddr: 0x1000076A4, symSize: 0x42C }
  - { offsetInCU: 0x13AE9, offset: 0x13AE9, size: 0x8, addend: 0x0, symName: __ZNSt6vectorIiSaIiEED1Ev, symObjAddr: 0x10, symBinAddr: 0x100007530, symSize: 0x20 }
  - { offsetInCU: 0x13C43, offset: 0x13C43, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x680, symBinAddr: 0x100007AD0, symSize: 0x84 }
  - { offsetInCU: 0x13C4B, offset: 0x13C4B, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_1986B.cpp, symObjAddr: 0x704, symBinAddr: 0x100007B54, symSize: 0x3C }
  - { offsetInCU: 0x13CCA, offset: 0x13CCA, size: 0x8, addend: 0x0, symName: __Z5solvev, symObjAddr: 0x184, symBinAddr: 0x1000076A4, symSize: 0x42C }
  - { offsetInCU: 0x13CD2, offset: 0x13CD2, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x5B0, symBinAddr: 0x10000C0C0, symSize: 0x0 }
  - { offsetInCU: 0x14D93, offset: 0x14D93, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x5B0, symBinAddr: 0x10000C0C0, symSize: 0x0 }
  - { offsetInCU: 0x14DB5, offset: 0x14DB5, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x5B0, symBinAddr: 0x10000C0C0, symSize: 0x0 }
  - { offsetInCU: 0x14DED, offset: 0x14DED, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x5B0, symBinAddr: 0x10000C0C0, symSize: 0x0 }
  - { offsetInCU: 0x14E25, offset: 0x14E25, size: 0x8, addend: 0x0, symName: GCC_except_table0, symObjAddr: 0x5B0, symBinAddr: 0x10000C0C0, symSize: 0x0 }
  - { offsetInCU: 0x14ECB, offset: 0x14ECB, size: 0x8, addend: 0x0, symName: __ZNKSt5ctypeIcE8do_widenEc, symObjAddr: 0x0, symBinAddr: 0x100007520, symSize: 0x10 }
...
